---
ip_nfss: 192.168.56.10
ip_nfsc: 192.168.56.11
path_exports: /etc/exports
conf_exports: /srv/share 192.168.56.11/32(rw,sync,root_squash)
path_upload: /srv/share/upload
path_share: /srv/share
path_share_dir: /srv/share/upload
path_mdstat: /proc/mdstat
path_raid_disk: /dev/md0
sections:
  - {"path": "/raid/part1", "src": "/dev/md0p1"}
  - {"path": "/raid/part2", "src": "/dev/md0p2"}
  - {"path": "/raid/part3", "src": "/dev/md0p3"}
  - {"path": "/raid/part4", "src": "/dev/md0p4"}
  - {"path": "/raid/part5", "src": "/dev/md0p5"}
