---
- name: zero superblock
  shell: "mdadm --zero-superblock --force /dev/sd{b,c,d,e,f}"
  tags: zero

- name: create new raid
  shell: "mdadm --create --verbose {{ path_raid_disk }} -l 6 -n 5 /dev/sd{b,c,d,e,f}"
  tags: create

- name: "add variable raid_check"
  shell: "cat {{ path_mdstat }} | grep md0"
  register: raid_check
  tags: info

- name: "Print riad_check"
  ansible.builtin.debug:
    var: "raid_check.stdout"
  tags: info

- name: "create dir"
  ansible.builtin.file:
    path: "{{ path_mdadm_dir }}"
    state: directory
  tags: mkdir_mdadm

- name: "create file"
  file:
    path: "{{ path_conf_file }}"
    state: touch
#    owner: root
#    group: root
#    mode: '766'
  tags: mkfile

- name: "add array description"
  shell: |
    echo "DEVICE partitions" > {{ path_conf_file }}
    mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> {{ path_conf_file }}
  tags: conf_file

- name: "part raid sections"
  shell: |
    parted -s {{ path_raid_disk }} mklabel gpt
    parted {{ path_raid_disk }} mkpart primary ext4 0% 20%
    parted {{ path_raid_disk }} mkpart primary ext4 20% 40%
    parted {{ path_raid_disk }} mkpart primary ext4 40% 60%
    parted {{ path_raid_disk }} mkpart primary ext4 60% 80%
    parted {{ path_raid_disk }} mkpart primary ext4 80% 100%
  tags: part

- name: "Create a ext4 filesystem"
  community.general.filesystem:
    fstype: ext4
    dev: "{{ item.src }}"
  with_items: "{{ sections }}"
  tags: mkfs

- name: "create dir"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
  with_items: "{{ sections }}"
  tags: mkdir_raid

- name: "mount storage and update /etc/fstab"
  mount:
    state: mounted
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
  with_items: "{{ sections }}"
  tags: mount
